config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#Index"
  resources :has_stores
  resources :stores
  resources :products
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: "Tienda Agregada Correctamente." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Tienda Actualizada Correctamente." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Tienda Eliminada Correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:Name, :Street, :Number, :ZipCode, :Country, :Products)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :Street %>
    <%= form.text_field :Street %>
  </div>

  <div class="field">
    <%= form.label :Number %>
    <%= form.number_field :Number %>
  </div>

  <div class="field">
    <%= form.label :ZipCode %>
    <%= form.text_field :ZipCode %>
  </div>

  <div class="field">
    <%= form.label :Country %>
    <%= form.text_field :Country %>
  </div>

  <div class="field">
    <%= form.label :Products %>
    <%= form.text_field :Products %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editar Tienda</h1>

<%= render 'form', store: @store %>

<%= link_to 'Ver', @store %> |
<%= link_to 'Atras', stores_path %>

app/views/stores/index.html.erb
<style>
  .TablaPrincipal{
    width: 100%; 
    text-align: center;
    background: black;
  }

  .TablaCabecera{
    background-color: aliceblue;
  }

  .TablaCuerpo{
    background-color: white;
  }

  td {
      padding: 2px;
  }

  th {
    padding-bottom: 0px;
    padding: 2px;
  }
</style>



<p id="notice"><%= notice %></p>

<h1>Tiendas</h1>

<table class="TablaPrincipal">

  <thead class="TablaCabecera">
    <tr>
      <th>Nombre</th>
      <th>Calle</th>
      <th>Numero</th>
      <th>Codigo Postal</th>
      <th>Pais</th>
      <th>Producto</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody class="TablaCuerpo">
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.Name %></td>
        <td><%= store.Street %></td>
        <td><%= store.Number %></td>
        <td><%= store.ZipCode %></td>
        <td><%= store.Country %></td>
        <td><%= store.Products %></td>
        <td><%= link_to 'Ver', store %></td>
        <td><%= link_to 'Editar', edit_store_path(store) %></td>
        <td><%= link_to 'Eliminar', store, method: :delete, data: { confirm: 'Seguro de Elimnar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo', new_store_path %>

<%= link_to 'Atras', "../" %>

app/views/stores/new.html.erb
<h1>Agregar Tienda</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @store.Name %>
</p>

<p>
  <strong>Calle:</strong>
  <%= @store.Street %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @store.Number %>
</p>

<p>
  <strong>Codigo Postal:</strong>
  <%= @store.ZipCode %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @store.Country %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @store.Products %>
</p>

<%= link_to 'Editar', edit_store_path(@store) %> |
<%= link_to 'Atras', stores_path %>