config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#Index"
  resources :has_stores
  resources :stores
  resources :products
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/has_store.rb
class HasStore < ApplicationRecord
end

app/controllers/has_stores_controller.rb
class HasStoresController < ApplicationController
  before_action :set_has_store, only: %i[ show edit update destroy ]

  # GET /has_stores or /has_stores.json
  def index
    @has_stores = HasStore.all
  end

  # GET /has_stores/1 or /has_stores/1.json
  def show
  end

  # GET /has_stores/new
  def new
    @has_store = HasStore.new
  end

  # GET /has_stores/1/edit
  def edit
  end

  # POST /has_stores or /has_stores.json
  def create
    @has_store = HasStore.new(has_store_params)

    respond_to do |format|
      if @has_store.save
        format.html { redirect_to @has_store, notice: "Has store was successfully created." }
        format.json { render :show, status: :created, location: @has_store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @has_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /has_stores/1 or /has_stores/1.json
  def update
    respond_to do |format|
      if @has_store.update(has_store_params)
        format.html { redirect_to @has_store, notice: "Has store was successfully updated." }
        format.json { render :show, status: :ok, location: @has_store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @has_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /has_stores/1 or /has_stores/1.json
  def destroy
    @has_store.destroy
    respond_to do |format|
      format.html { redirect_to has_stores_url, notice: "Has store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_has_store
      @has_store = HasStore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def has_store_params
      params.require(:has_store).permit(:Product, :Store)
    end
end

app/helpers/has_stores_helper.rb
module HasStoresHelper
end

app/views/has_stores/_form.html.erb
<%= form_with(model: has_store) do |form| %>
  <% if has_store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(has_store.errors.count, "error") %> prohibited this has_store from being saved:</h2>

      <ul>
        <% has_store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Product %>
    <%= form.text_field :Product %>
  </div>

  <div class="field">
    <%= form.label :Store %>
    <%= form.text_field :Store %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/has_stores/edit.html.erb
<h1>Editing Has Store</h1>

<%= render 'form', has_store: @has_store %>

<%= link_to 'Show', @has_store %> |
<%= link_to 'Back', has_stores_path %>

app/views/has_stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Has Stores</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @has_stores.each do |has_store| %>
      <tr>
        <td><%= has_store.Product %></td>
        <td><%= has_store.Store %></td>
        <td><%= link_to 'Show', has_store %></td>
        <td><%= link_to 'Edit', edit_has_store_path(has_store) %></td>
        <td><%= link_to 'Destroy', has_store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Has Store', new_has_store_path %>

app/views/has_stores/new.html.erb
<h1>New Has Store</h1>

<%= render 'form', has_store: @has_store %>

<%= link_to 'Back', has_stores_path %>

app/views/has_stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @has_store.Product %>
</p>

<p>
  <strong>Store:</strong>
  <%= @has_store.Store %>
</p>

<%= link_to 'Edit', edit_has_store_path(@has_store) %> |
<%= link_to 'Back', has_stores_path %>